const state={contents:[],trash:[],backups:[],tasks:[],chatSources:[],chatRegistrations:[],categories:[],weeklyPlans:[],pendingAgentReviews:[],agentReviewHistory:[],agentReviewMode:"pending",agentReviewProjectId:null,activeAgentReviewId:null,activeAgentReviewHistoryId:null,selectedCandidateIndexes:[],settings:{},system:{},filter:"all",categoryFilter:null,editId:null,categoryEditId:null,taskSourceId:null,currentWeek:null,historyWeek:null,onboardingStep:0,chatHistory:[]};
const labels={knowledge:"知识",book:"书籍",media:"媒体",thought:"想法",journal:"日记",project:"项目","chat-note":"聊天知识"};
const $=(selector,root=document)=>root.querySelector(selector), $$=(selector,root=document)=>[...root.querySelectorAll(selector)];

async function api(path,options={}){const response=await fetch(path,{headers:{"Content-Type":"application/json"},...options});const data=await response.json();if(!response.ok)throw new Error(data.error||"操作失败");return data}
function escapeHtml(value=""){return String(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]))}
function formatDate(value){return value?new Intl.DateTimeFormat("zh-CN",{month:"short",day:"numeric"}).format(new Date(value)):""}
function dateKey(value){const date=value instanceof Date?value:new Date(value);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`}
function startOfWeek(value){const date=new Date(value);date.setHours(0,0,0,0);date.setDate(date.getDate()-((date.getDay()+6)%7));return date}
function addDays(value,amount){const date=new Date(value);date.setDate(date.getDate()+amount);return date}
function weekLabel(start){const end=addDays(start,6);return `${start.getMonth()+1}月${start.getDate()}日—${end.getMonth()+1}月${end.getDate()}日`}
function taskSlot(task){if(!task.scheduled_time)return "all";const hour=Number(task.scheduled_time.slice(0,2));return hour<12?"morning":hour<18?"afternoon":"evening"}
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)}
async function load(){const [bootstrap,pendingAgentReviews,agentReviewHistory]=await Promise.all([api("/api/bootstrap"),api("/api/agent-candidate-results/pending"),api("/api/agent-candidate-results/history")]);Object.assign(state,bootstrap,{pendingAgentReviews,agentReviewHistory});renderAll()}
function renderAll(){if(!state.currentWeek)state.currentWeek=startOfWeek(new Date());renderTasks();renderReading();renderRecent();renderCategoryMap();renderCategorySelects();renderLibrary();renderSources();renderWeekCalendar();renderAgentReview();renderReview();renderTaskHistory();renderDataManagement();$("#baseUrl").value=state.settings.base_url||"https://api.openai.com/v1";$("#modelName").value=state.settings.model||"";$("#apiKey").value=state.settings.api_key||"";}

function renderTasks(){const today=dateKey(new Date());const open=state.tasks.filter(task=>task.status!=="done"&&task.due_date&&task.due_date<=today).sort((a,b)=>(a.scheduled_time||"").localeCompare(b.scheduled_time||"")).slice(0,8);$("#todayTasks").innerHTML=open.length?open.map(task=>`<div class="task-item"><button class="task-check" data-task-id="${task.id}" aria-label="完成待办"></button><div><div class="task-title">${escapeHtml(task.title)}</div><div class="task-meta">${task.due_date<today?"已逾期 · ":""}${task.scheduled_time||"全天"} · ${escapeHtml(task.source_title||"独立待办")}</div></div><i class="priority-dot ${task.priority}"></i></div>`).join(""):'<div class="empty-state">今天没有待办，留一点空间给重要的事。</div>';$$('[data-task-id]').forEach(button=>button.addEventListener("click",()=>updateTask(button.dataset.taskId,"done")))}
function renderReading(){const book=state.contents.find(item=>item.type==="book");$("#readingCard").innerHTML=book?`<div class="book-cover"><span>正在阅读</span><strong>${escapeHtml(book.title)}</strong></div><div class="progress-line"><i></i></div><div class="book-meta"><span>${escapeHtml(book.category||"未分类")}</span><span>36%</span></div>`:'<div class="empty-state">还没有读书记录</div>'}
function renderRecent(){const items=state.contents.filter(item=>["knowledge","thought","chat-note"].includes(item.type)).slice(0,4);$("#recentKnowledge").innerHTML=items.map(item=>`<div class="recent-item"><strong>${escapeHtml(item.title)}</strong><span>${labels[item.type]} · ${escapeHtml(categoryLabel(item.category_id)||"未分类")}</span></div>`).join("")}
function itemTags(item){return String(item.tags||"").split(",").map(tag=>tag.trim()).filter(Boolean)}
function categoryById(id){return state.categories.find(item=>item.id===Number(id))}
function categoryLabel(id){const names=[];let current=categoryById(id);while(current){names.unshift(current.name);current=categoryById(current.parent_id)}return names.join(" / ")}
function categoryDescendants(id){const ids=[Number(id)];for(let index=0;index<ids.length;index++)state.categories.filter(item=>item.parent_id===ids[index]).forEach(item=>ids.push(item.id));return ids}
function categoryTree(items,parentId=null){return items.filter(item=>(item.parent_id||null)===parentId).map(item=>{const count=state.contents.filter(content=>categoryDescendants(item.id).includes(content.category_id)&&(state.filter==="all"||content.type===state.filter)).length;return `<li><div class="category-card ${state.categoryFilter===item.id?"active":""}"><button class="category-select" data-category-filter="${item.id}"><span>${escapeHtml(item.name)}</span><small>${labels[item.content_type]} · ${count} 条</small></button><button class="category-child" data-category-parent="${item.id}" aria-label="在 ${escapeHtml(item.name)} 下创建子分类">＋ 子卡片</button><button class="category-edit" data-category-edit="${item.id}" aria-label="编辑 ${escapeHtml(item.name)}">•••</button></div>${categoryTree(items,item.id)}</li>`}).join("")}
function renderCategoryMap(){const items=state.categories.filter(item=>state.filter==="all"||item.content_type===state.filter);$("#categoryMap").innerHTML=items.length?`<button class="category-all ${state.categoryFilter===null?"active":""}" data-category-filter="all">全部内容</button><div class="category-tree"><ul>${categoryTree(items)}</ul></div>`:'<div class="empty-state">还没有分类卡片。创建第一张卡片后，可以继续在它下面添加子卡片。</div>'}
function categoryOptions(contentType,selected,excludedIds=[]){const excluded=new Set(excludedIds.map(Number)),items=state.categories.filter(item=>item.content_type===contentType&&!excluded.has(item.id));const walk=(parentId=null,depth=0)=>items.filter(item=>(item.parent_id||null)===parentId).map(item=>`<option value="${item.id}" ${Number(selected)===item.id?"selected":""}>${"　".repeat(depth)}${escapeHtml(item.name)}</option>${walk(item.id,depth+1)}`).join("");return `<option value="">未分类</option>${walk()}`}
function allCategoryOptions(selected){const groups=Object.entries(labels).map(([type,label])=>{const options=categoryOptions(type,selected).replace('<option value="">未分类</option>',"");return options?`<optgroup label="${escapeHtml(label)}">${options}</optgroup>`:""}).join("");return `<option value="">未分类（保存为聊天知识）</option>${groups}`}
function renderCategorySelects(){const editType=$("#editType").value||"thought",excluded=state.categoryEditId?categoryDescendants(state.categoryEditId):[];$("#editCategory").innerHTML=categoryOptions(editType,$("#editCategory").value);$("#categoryParent").innerHTML=categoryOptions($("#categoryType").value||"knowledge",$("#categoryParent").value,excluded).replace(">未分类<",">无母卡（作为根卡片）<");$("#markdownCategory").innerHTML=allCategoryOptions($("#markdownCategory").value)}
function openCategoryDialog(parentId=null,categoryId=null){state.categoryEditId=categoryId;const category=categoryById(categoryId);$("#categoryDialogTitle").textContent=category?"编辑分类卡片":"新建分类卡片";$("#categoryName").value=category?.name||"";$("#categoryType").value=category?.content_type||(parentId?categoryById(parentId)?.content_type:(state.filter==="all"?"knowledge":state.filter));$("#categoryType").disabled=Boolean(category);renderCategorySelects();$("#categoryParent").value=category?.parent_id||parentId||"";$("#deleteCategoryButton").hidden=!category;$("#categoryDialog").showModal()}
function renderLibrary(){
  const query=$("#librarySearch").value.trim().toLowerCase(),access=$("#sourceAccessFilter").value;
  const categoryIds=state.categoryFilter===null?null:categoryDescendants(state.categoryFilter);
  const items=state.contents.filter(item=>(access==="all"||String(item.ai_access)===access)&&(!categoryIds||categoryIds.includes(item.category_id))&&(!query||`${item.id} ${item.title} ${item.tags} ${item.body} ${item.source}`.toLowerCase().includes(query)));
  $("#libraryGrid").innerHTML=items.length?items.map(item=>`<article class="content-card"><span class="type">来源 #${escapeHtml(item.id)} · ${item.ai_access===1?"允许 AI 使用":"禁止 AI 使用"}</span><h3>${escapeHtml(item.title)}</h3><div class="content-category">${escapeHtml(categoryLabel(item.category_id)||"未分类")}</div><p>${escapeHtml(item.body||"暂无正文，请补充交付依据。")}</p><details><summary>查看完整依据</summary><div style="white-space:pre-wrap;overflow-wrap:anywhere;font-size:13px;max-height:320px;overflow:auto">${escapeHtml(item.body||"暂无正文")}</div></details><div class="content-foot"><span>来源渠道：${escapeHtml(item.source||"未记录")}<br>更新：${escapeHtml(item.updated_at||"未记录")}</span></div><div class="content-foot"><span class="card-actions"><button class="card-action" data-edit-content="${item.id}">编辑资料</button><button class="card-action danger-link" data-delete-content="${item.id}">移至回收站</button></span></div></article>`).join(""):'<div class="empty-state">没有符合条件的资料。可调整筛选，或使用右上角“添加资料”。</div>';
}
function renderSources(){$("#chatSources").innerHTML=state.chatRegistrations.length?state.chatRegistrations.map(source=>`<div class="source-row"><div><strong>${escapeHtml(source.display_name)}</strong><span>${escapeHtml(source.path)}</span></div><span>${source.last_run_at?`最近检查 ${formatDate(source.last_run_at)}`:"等待首次归档"}</span></div>`).join(""):'<div class="empty-state">还没有登记聊天路径。</div>';$("#archiveAllSources").disabled=!state.chatRegistrations.length}
function renderWeekCalendar(){
  const start=state.currentWeek,days=Array.from({length:7},(_,index)=>addDays(start,index));
  $("#weekRange").textContent=weekLabel(start);
  const plan=state.weeklyPlans.find(item=>item.week_start===dateKey(start));
  $("#weekPlanText").value=plan?.plan_text||"";
  $("#weekPlanStatus").textContent=plan?.updated_at?`已保存 · ${formatDate(plan.updated_at)}`:"按周保存在本机";
  const weekdays=["周一","周二","周三","周四","周五","周六","周日"],today=dateKey(new Date());
  const slots=[{id:"all",name:"全天",range:"未指定时间"},{id:"morning",name:"上午",range:"06:00—12:00"},{id:"afternoon",name:"下午",range:"12:00—18:00"},{id:"evening",name:"晚上",range:"18:00—24:00"}];
  let html='<div class="calendar-corner">日期 / 时间</div>'+days.map((day,index)=>`<button class="day-head ${dateKey(day)===today?"today":""}" data-calendar-date="${dateKey(day)}"><span>${weekdays[index]}</span><strong>${day.getDate()}</strong></button>`).join("");
  for(const slot of slots){html+=`<div class="time-head"><strong>${slot.name}</strong>${slot.range}</div>`;for(const [index,day] of days.entries()){const key=dateKey(day);const tasks=state.tasks.filter(task=>task.due_date===key&&taskSlot(task)===slot.id).sort((a,b)=>(a.scheduled_time||"").localeCompare(b.scheduled_time||""));html+=`<div class="calendar-cell ${index>4?"weekend":""}" data-cell-date="${key}" data-cell-slot="${slot.id}">${tasks.map(task=>`<div class="calendar-task ${task.priority} ${task.status==="done"?"done":""}" data-calendar-task="${task.id}" title="点击切换完成状态"><time>${task.scheduled_time||"全天"}</time>${escapeHtml(task.title)}</div>`).join("")}${tasks.length?"":`<button class="calendar-empty-add" aria-label="添加待办">＋</button>`}</div>`}}
  $("#weekCalendar").innerHTML=html;
}

function availableWeeks(){
  const keys=new Set([dateKey(startOfWeek(new Date()))]);
  for(let index=0;index<12;index++)keys.add(dateKey(addDays(startOfWeek(new Date()),-7*index)));
  state.tasks.filter(task=>task.due_date).forEach(task=>keys.add(dateKey(startOfWeek(new Date(`${task.due_date}T12:00:00`)))));
  state.weeklyPlans.forEach(plan=>keys.add(plan.week_start));
  return [...keys].sort().reverse();
}
function renderTaskHistory(){
  const weeks=availableWeeks();if(!state.historyWeek||!weeks.includes(state.historyWeek))state.historyWeek=weeks[0];
  $("#historyWeekSelect").innerHTML=weeks.map(key=>`<option value="${key}" ${key===state.historyWeek?"selected":""}>${weekLabel(new Date(`${key}T12:00:00`))}</option>`).join("");
  const start=new Date(`${state.historyWeek}T12:00:00`),end=addDays(start,6),tasks=state.tasks.filter(task=>task.due_date&&task.due_date>=dateKey(start)&&task.due_date<=dateKey(end)).sort((a,b)=>`${a.due_date}${a.scheduled_time}`.localeCompare(`${b.due_date}${b.scheduled_time}`));
  const done=tasks.filter(task=>task.status==="done").length,plan=state.weeklyPlans.find(item=>item.week_start===state.historyWeek);
  $("#taskHistory").innerHTML=`<div class="history-summary"><span><strong>${tasks.length}</strong> 项计划</span><span><strong>${done}</strong> 项完成</span><span><strong>${tasks.length?Math.round(done/tasks.length*100):0}%</strong> 完成率</span></div>${plan?.plan_text?`<div class="history-plan"><strong>周计划</strong>\n${escapeHtml(plan.plan_text)}</div>`:""}${tasks.length?tasks.map(task=>`<div class="history-task-row"><time>${formatDate(task.due_date)} ${task.scheduled_time||"全天"}</time><span class="${task.status==="done"?"done":""}">${escapeHtml(task.title)}</span><span class="history-state">${task.status==="done"?"已完成":task.status==="doing"?"进行中":"未完成"}</span></div>`).join(""):'<div class="empty-state">这一周还没有待办记录。</div>'}`;
}
function activeAgentReview(){return state.pendingAgentReviews.find(item=>item.id===state.activeAgentReviewId)}
function defaultCandidateIndexes(item){const candidates=item?.result?.candidates||[];return candidates.length===1?[0]:[]}
function candidateEvidence(candidate){const evidence=Array.isArray(candidate.evidence)?candidate.evidence:[];return evidence.length?evidence.map(item=>`<div class="candidate-evidence"><strong>字段 ${escapeHtml(item.candidate_field||"未标明")}</strong><br>${escapeHtml(item.evidence_excerpt||"没有摘录")}<br><span>Source ${escapeHtml(item.source_id)} · ${escapeHtml(item.source_locator?.value||"未定位")}</span></div>`).join(""):'<div class="candidate-evidence">当前候选没有字段级证据摘录。</div>'}
function agentActionLabel(value){return {extract_deliverables:"整理交付成果候选"}[value]||"受控整理任务"}
function forbiddenScopeLabel(value){return {formal_business_writes:"不得直接修改正式交付数据",duplicate_runs:"不得重复运行同一任务"}[value]||"其他受限操作"}
function renderUnknowns(unknowns){const items=Array.isArray(unknowns)?unknowns:[];return `<div class="review-unknowns ${items.length?"":"clear"}"><strong>待补充与确认</strong>${items.length?`<p>这些信息可能缺失、含糊或相互冲突，需要负责人补充或确认，不会被当作确定事实。</p><div class="unknown-stack">${items.map(item=>`<div class="unknown-item"><strong>${escapeHtml(item.field||"未标明字段")}</strong><span>${escapeHtml(item.reason||"授权资料不足，需负责人确认")}</span><small>已检查来源：${(item.checked_source_ids||[]).map(id=>`#${escapeHtml(id)}`).join("、")||"未记录"}</small></div>`).join("")}</div>`:"<p>本次没有待补充的信息；负责人仍需核对候选与证据。</p>"}</div>`}
function reviewDraftDefaults(item,selected){
  const dates=[...new Set(selected.map(candidate=>String(candidate.due_at||"").trim()).filter(Boolean))],
    criteria=[...new Set(selected.map(candidate=>String(candidate.acceptance_criteria||"").trim()).filter(Boolean))],
    matching=selected.length===1?(item.project.deliverables||[]).find(deliverable=>String(deliverable.title||"").trim().toLowerCase()===String(selected[0].title||"").trim().toLowerCase()):null;
  return {
    title:selected.map(candidate=>String(candidate.title||"").trim()).join("和"),
    dueAt:dates.length===1?dates[0]:"",
    acceptance:criteria.join("\n"),
    scope:String(item.project.scope||"").trim(),
    owner:"",
    approver:String(item.project.owner||"").trim(),
    target:matching?String(matching.id):"",
    reason:selected.length>1?"多个候选共同验收，合并管理":matching?"验收标准发生变化，建立新版本保留历史":"已核对候选及字段级证据",
    matching,
  };
}
function updateReviewAction(){
  const item=activeAgentReview(),button=$("#reviewCandidateButton");
  if(!item||!button)return;
  const indexes=[...state.selectedCandidateIndexes].sort((a,b)=>a-b),
    selected=indexes.map(index=>item.result.candidates[index]).filter(Boolean),
    defaults=reviewDraftDefaults(item,selected),
    title=$("#reviewedTitle").value.trim(),
    dueAt=$("#reviewedDueDate").value,
    acceptance=$("#reviewedAcceptanceCriteria").value.trim(),
    scope=$("#reviewedScope").value.trim(),
    owner=$("#reviewedOwner").value.trim(),
    approver=$("#reviewedApprover").value.trim(),
    reason=$("#reviewReason").value.trim(),
    hasRequiredFields=Boolean(selected.length&&title&&dueAt&&acceptance&&scope&&owner&&approver),
    candidateMerged=selected.length>1,
    target=$("#reviewTargetDeliverable").value,
    preview=$("#reviewWritePreview");
  const targetLabel=value=>{const existing=(item.project.deliverables||[]).find(deliverable=>String(deliverable.id)===String(value));return existing?`为“${existing.title}”创建第${existing.revision_no+1}版`:"新建交付成果"},
    fieldChanges=[],
    recordChange=(label,before,after,format=value=>String(value||"未填写"))=>{if(String(before)!==String(after))fieldChanges.push({label,before:format(before),after:format(after)})};
  recordChange("写入位置",defaults.target,target,targetLabel);
  recordChange("交付成果名称",defaults.title,title);
  recordChange("截止日期",defaults.dueAt,dueAt);
  recordChange("验收标准",defaults.acceptance,acceptance);
  recordChange("交付范围",defaults.scope,scope);
  recordChange("交付负责人",defaults.owner,owner,value=>String(value||"未指定"));
  recordChange("验收负责人",defaults.approver,approver,value=>String(value||"未指定"));
  recordChange("审查说明",defaults.reason,reason);
  const destination=target?"新版本":"待确认成果";
  button.disabled=!hasRequiredFields;
  button.textContent=!selected.length?"请先选择候选":!hasRequiredFields?"请补齐正式草稿字段":`确认并创建${destination}`;
  if(!preview)return;
  if(!selected.length){preview.innerHTML='<strong>正式写入预览</strong><p>尚未选择候选，不会创建正式交付成果或版本。</p>';return}
  const selectionText=candidateMerged?`合并候选 ${indexes.map(index=>`#${index+1}`).join("、")}`:`采用候选 #${indexes[0]+1}`,
    changesMarkup=fieldChanges.length?`<ul>${fieldChanges.map(change=>`<li><strong>${escapeHtml(change.label)}</strong><span>${escapeHtml(change.before)} → ${escapeHtml(change.after)}</span></li>`).join("")}</ul>`:"<p>自动填充字段未修改。</p>";
  preview.innerHTML=`<strong>正式写入预览</strong><div class="review-change-summary"><div><span>采纳方式</span><strong>${escapeHtml(selectionText)}</strong></div><div><span>写入位置</span><strong>${escapeHtml(targetLabel(target))}</strong></div><div><span>与自动填充相比</span>${changesMarkup}</div></div><h4>最终写入内容</h4><div class="review-preview-grid"><span>交付成果名称<strong>${escapeHtml(title||"待填写")}</strong></span><span>截止日期<strong>${escapeHtml(dueAt||"待填写")}</strong></span><span>验收标准<strong>${escapeHtml(acceptance||"待填写")}</strong></span><span>交付范围<strong>${escapeHtml(scope||"待填写")}</strong></span><span>执行负责人<strong>${escapeHtml(owner||"待填写")}</strong></span><span>验收负责人<strong>${escapeHtml(approver||"待填写")}</strong></span><span>是否必交<strong>是</strong></span><span>日期状态<strong>已确认</strong></span><span>版本状态<strong>待负责人确认</strong></span></div><p><strong>审查说明：</strong>${escapeHtml(reason||"待填写")}</p><p>点击提交前不会写入正式业务表；提交后仍需负责人确认。</p>`;
}
function syncReviewDraft(){const item=activeAgentReview();if(!item)return;const indexes=[...state.selectedCandidateIndexes].sort((a,b)=>a-b),selected=indexes.map(index=>item.result.candidates[index]).filter(Boolean),defaults=reviewDraftDefaults(item,selected);$("#reviewedTitle").value=defaults.title;$("#reviewedDueDate").value=defaults.dueAt;$("#reviewedAcceptanceCriteria").value=defaults.acceptance;$("#reviewTargetDeliverable").value=defaults.target;$("#reviewSelectionHint").textContent=defaults.matching?`已匹配现有交付物 #${defaults.matching.id}；将保留旧版并建立第${defaults.matching.revision_no+1}版。`:`已选择 ${selected.length} 个原候选；原始结果不会被覆盖。`;$("#reviewReason").value=defaults.reason;updateReviewAction()}
function reviewDecisionLabel(decision){return {accepted:"已采用原候选",modified:"修改后采用",rejected:"已拒绝"}[decision]||decision}
function revisionStatusLabel(status){return {draft:"待负责人确认",confirmed:"已确认",doing:"执行中",submitted:"已提交",accepted:"已验收"}[status]||status}
function renderAgentReviewHistory(items){
  $("#agentReviewQueueTitle").textContent="已处理记录";
  if(!items.some(item=>item.review.id===state.activeAgentReviewHistoryId))state.activeAgentReviewHistoryId=items[0]?.review.id||null;
  $("#agentReviewQueue").innerHTML=items.length?items.map(item=>`<button class="review-queue-item ${item.review.id===state.activeAgentReviewHistoryId?"active":""}" data-agent-review-history-id="${item.review.id}"><strong>${escapeHtml(item.project.name||`项目 ${item.project.id}`)}</strong><span>${escapeHtml(reviewDecisionLabel(item.review.decision))} · 整理任务 ${item.agent_job.id}</span></button>`).join(""):'<div class="empty-state review-empty">还没有处理记录。负责人接受、修改或拒绝候选后，会在这里留下可追溯记录。</div>';
  const item=items.find(entry=>entry.review.id===state.activeAgentReviewHistoryId),workspace=$("#agentReviewWorkspace");
  if(!item){workspace.innerHTML='<div class="panel empty-next-action"><strong>还没有处理记录</strong><p>先授权资料并运行整理任务；负责人作出决定后，原候选、决定和原因会保留在这里。</p><button class="primary-button" type="button" data-review-go-projects>返回项目并生成交付建议</button></div>';return}
  const candidates=item.original_result.candidates||[],sources=item.allowed_sources.map(source=>`#${source.id} ${source.title}`).join("、")||"未记录",outputs=item.outputs||[];
  workspace.innerHTML=`<section class="panel review-history-detail"><span class="section-kicker">REVIEW HISTORY</span><h3>${escapeHtml(reviewDecisionLabel(item.review.decision))}</h3><div class="review-contract-grid"><div class="contract-field"><span>所属项目</span><strong>${escapeHtml(item.project.name||`项目 ${item.project.id}`)} · 第${item.project.cycle_no||"?"}周期</strong></div><div class="contract-field"><span>负责人决定</span><strong>${escapeHtml(item.review.actor)} · ${escapeHtml(item.review.created_at)}</strong></div><div class="contract-field"><span>本次授权来源</span><strong>${escapeHtml(sources)}</strong></div><div class="contract-field"><span>决定原因</span><strong>${escapeHtml(item.review.reason||"未填写")}</strong></div></div><h4>保留的原始候选</h4><div class="review-history-candidates">${candidates.map((candidate,index)=>`<div><strong>#${index+1} ${escapeHtml(candidate.title||"未命名候选")}</strong><span>截止日期：${escapeHtml(candidate.due_at||"待确认")} · 验收标准：${escapeHtml(candidate.acceptance_criteria||"待确认")}</span></div>`).join("")||"<p>没有候选内容。</p>"}</div><h4>形成的正式记录</h4>${outputs.length?`<div class="review-history-outputs">${outputs.map(output=>`<button type="button" data-review-output-project="${item.project.id}" data-review-output-deliverable="${output.deliverable_id}" data-review-output-revision="${output.revision_id}">${escapeHtml(output.title)} · 第${output.revision_no}版 · ${revisionStatusLabel(output.status)}</button>`).join("")}</div>`:'<p>本次建议被拒绝，没有创建交付成果或版本。</p>'}</section>`;
}
function renderAgentReview(){
  const projectId=state.agentReviewProjectId,items=state.pendingAgentReviews.filter(item=>!projectId||item.project.id===projectId),history=state.agentReviewHistory.filter(item=>!projectId||item.project.id===projectId);
  $("#pendingReviewCount").textContent=String(items.length);
  $("#agentReviewHistoryCount").textContent=String(history.length);
  $("#pendingReviewMode").classList.toggle("active",state.agentReviewMode==="pending");
  $("#reviewHistoryMode").classList.toggle("active",state.agentReviewMode==="history");
  if(state.agentReviewMode==="history"){renderAgentReviewHistory(history);return}
  $("#agentReviewQueueTitle").textContent="待审任务";
  if(!items.some(item=>item.id===state.activeAgentReviewId)){
    state.activeAgentReviewId=items[0]?.id||null;
    state.selectedCandidateIndexes=defaultCandidateIndexes(items[0]);
  }
  $("#agentReviewQueue").innerHTML=items.length?items.map(item=>`<button class="review-queue-item ${item.id===state.activeAgentReviewId?"active":""}" data-agent-review-id="${item.id}"><strong>${escapeHtml(item.project.name||`项目 ${item.project.id}`)}</strong><span>整理任务 ${item.agent_job.id} · ${item.result.candidates.length} 个候选</span></button>`).join(""):'<div class="empty-state review-empty">当前没有待审任务</div>';
  const item=activeAgentReview(),workspace=$("#agentReviewWorkspace");
  if(!item){workspace.innerHTML='<div class="panel empty-next-action"><strong>当前没有等待负责人处理的建议</strong><p>先授权资料并运行整理任务；生成的候选会先到这里，不会直接写入交付清单。</p><button class="primary-button" type="button" data-review-go-projects>返回项目并生成交付建议</button></div>';return}
  const contract=item.agent_job.request_contract,
    candidates=item.result.candidates||[],
    allowed=item.allowed_sources.map(source=>`#${source.id} ${escapeHtml(source.title)}`).join("、"),
    deliverables=item.project.deliverables||[],
    actionLabel=agentActionLabel(contract.action),
    forbiddenLabels=(contract.forbidden_scope||[]).map(forbiddenScopeLabel).join("、")||"无",
    selectionHelp=candidates.length>1?`本次有 ${candidates.length} 个候选，默认不选择。请逐项核对后决定单独采用或合并。`:'单个候选已选中；提交前仍需核对字段级证据和待补充与确认信息。';
  workspace.innerHTML=`<section class="panel review-contract"><span class="section-kicker">1 · 本次任务边界</span><h3>本次 AI 整理任务能做什么</h3><div class="review-contract-grid"><div class="contract-field"><span>要做的事</span><strong>${escapeHtml(actionLabel)}</strong></div><div class="contract-field"><span>授权来源</span><strong>${allowed||"无"}</strong></div><div class="contract-field"><span>具体要求</span><strong>${escapeHtml(contract.instruction)}</strong></div><div class="contract-field"><span>明确不能做</span><strong>${escapeHtml(forbiddenLabels)}</strong></div></div></section><section class="panel review-candidates"><span class="section-kicker">2 · AI 原始结果</span><h3>AI 原始候选</h3><p class="review-help">${escapeHtml(selectionHelp)} 原始结果会永久保留。</p><div id="candidateSelection" class="candidate-stack">${candidates.map((candidate,index)=>`<label class="candidate-card"><input type="checkbox" data-candidate-index="${index}" ${state.selectedCandidateIndexes.includes(index)?"checked":""}><div><h4>${escapeHtml(candidate.title||"未命名候选")}</h4><span class="candidate-meta">截止日期 ${escapeHtml(candidate.due_at||"待确认")} · 来源 ${(candidate.evidence_source_ids||[]).map(id=>`#${id}`).join("、")||"未标明"}</span>${candidateEvidence(candidate)}</div></label>`).join("")}</div>${renderUnknowns(item.result.unknowns)}</section><section class="panel review-draft"><span class="section-kicker">3 · 负责人决定</span><h3>准备创建的待确认成果</h3><form id="reviewCandidateForm"><label>写入位置<select id="reviewTargetDeliverable"><option value="">创建新的交付成果</option>${deliverables.map(deliverable=>`<option value="${deliverable.id}">已有：${escapeHtml(deliverable.title)} · 当前第${deliverable.revision_no}版</option>`).join("")}</select></label><div class="form-grid"><label>交付成果名称<input id="reviewedTitle" required></label><label>截止日期<input id="reviewedDueDate" type="date" required></label></div><label>验收标准<textarea id="reviewedAcceptanceCriteria" rows="3" required></textarea></label><label>交付范围<textarea id="reviewedScope" rows="3" required placeholder="负责人明确本成果包含什么、不包含什么">${escapeHtml(item.project.scope||"")}</textarea></label><div class="form-grid"><label>交付负责人<input id="reviewedOwner" required placeholder="谁负责执行"></label><label>验收负责人<input id="reviewedApprover" required value="${escapeHtml(item.project.owner||"")}"></label></div><label>审查原因<textarea id="reviewReason" rows="2" required></textarea></label><section id="reviewWritePreview" class="review-write-preview" aria-live="polite"></section><div class="draft-actions"><span id="reviewSelectionHint"></span><button id="reviewCandidateButton" class="primary-button" type="submit"></button></div><p id="reviewCandidateStatus" role="status"></p></form></section>`;
  workspace.insertAdjacentHTML("beforeend",'<section class="panel"><h3>拒绝本次建议</h3><p>拒绝后保留原候选和原因，不创建待确认成果。</p><form id="rejectCandidateForm"><label>拒绝原因<textarea id="rejectCandidateReason" required placeholder="例如：新日期缺少来源依据"></textarea></label><button class="secondary-button" type="submit">记录原因并拒绝</button><p id="rejectCandidateStatus" role="status"></p></form></section>');
  syncReviewDraft();
}
async function submitReviewedCandidate(){const item=activeAgentReview(),indexes=[...state.selectedCandidateIndexes].sort((a,b)=>a-b);if(!item||!indexes.length)return toast("请至少选择一个候选");const selected=indexes.map(index=>item.result.candidates[index]),title=$("#reviewedTitle").value.trim(),dueAt=$("#reviewedDueDate").value,acceptanceCriteria=$("#reviewedAcceptanceCriteria").value.trim(),original=selected[0],acceptingOriginal=item.result.candidates.length===1&&indexes.length===1&&indexes[0]===0&&title===String(original.title||"").trim()&&dueAt===String(original.due_at||"").trim()&&acceptanceCriteria===String(original.acceptance_criteria||"").trim(),decision=acceptingOriginal?"accepted":"modified",evidence=selected.flatMap(candidate=>candidate.evidence||[]),evidenceSourceIds=[...new Set(selected.flatMap(candidate=>candidate.evidence_source_ids||[]))],targetValue=$("#reviewTargetDeliverable").value,payload={decision,actor:item.project.owner,actor_role:"project_owner",reason:$("#reviewReason").value.trim(),formal_fields:{scope:$("#reviewedScope").value,owner:$("#reviewedOwner").value,approver:$("#reviewedApprover").value,due_date_status:"confirmed",is_required:true}};if(targetValue)payload.formal_fields.target_deliverable_id=Number(targetValue);if(decision==="modified")payload.reviewed_candidates=[{title,due_at:dueAt,acceptance_criteria:acceptanceCriteria,source_candidate_indexes:indexes,evidence_source_ids:evidenceSourceIds,evidence}];const button=$("#reviewCandidateButton"),status=$("#reviewCandidateStatus"),buttonText=button.textContent;button.disabled=true;button.textContent="正在创建待确认成果……";try{const result=await api(`/api/agent-candidate-results/${item.id}/reviews`,{method:"POST",body:JSON.stringify(payload)}),created=result.created_deliverables?.[0],revision=created?.current_revision;state.activeAgentReviewId=null;state.selectedCandidateIndexes=[];await load();if(created&&window.openCreatedDeliverable)await window.openCreatedDeliverable(item.project.id,created.id,revision?.id);toast(targetValue?"旧版已保留，新版本已创建并定位":decision==="accepted"?"候选已采用，待确认成果已创建并定位":"已保留原候选，修改后的待确认成果已创建并定位")}catch(error){status.textContent=error.message;button.disabled=false;button.textContent=buttonText}}
function renderReview(){const done=state.tasks.filter(task=>task.status==="done").length;const stats=[[state.contents.length,"知识与记录"],[state.contents.filter(item=>item.type==="book").length,"本月书籍"],[done,"已完成待办"],[state.chatRegistrations.length,"聊天来源"]];$("#reviewStats").innerHTML=stats.map(([value,label])=>`<div class="stat-card"><strong>${value}</strong><span>${label}</span></div>`).join("");$("#weeklyHighlights").innerHTML=state.contents.slice(0,5).map(item=>`<div class="review-item"><strong>${escapeHtml(item.title)}</strong><span>${labels[item.type]} · ${formatDate(item.updated_at)}</span></div>`).join("");$("#openLoops").innerHTML=state.tasks.filter(task=>task.status!=="done").slice(0,5).map(item=>`<div class="review-item"><strong>${escapeHtml(item.title)}</strong><span>${item.status==="doing"?"正在进行":"下一步"}</span></div>`).join("")}
function formatBytes(value){if(value<1024)return `${value} B`;if(value<1024*1024)return `${Math.round(value/1024)} KB`;return `${(value/1024/1024).toFixed(1)} MB`}
function renderDataManagement(){const selected=$("#backupSelect").value;$("#dataLocation").textContent=state.system.data_root||"当前项目目录";$("#schemaVersion").textContent=`v${state.system.schema_version||1}`;$("#appVersion").textContent=`Finto ${state.system.version||""}`;$("#backupSelect").innerHTML=state.backups.length?state.backups.map(item=>`<option value="${escapeHtml(item.name)}">${formatDate(item.created_at)} · ${formatBytes(item.size)}</option>`).join(""):'<option value="">还没有备份</option>';if(state.backups.some(item=>item.name===selected))$("#backupSelect").value=selected;$("#restoreBackupButton").disabled=!$("#backupSelect").value;$("#trashCount").textContent=`${state.trash.length} 条`;$("#trashList").innerHTML=state.trash.length?state.trash.map(item=>`<div class="trash-row"><div><strong>${escapeHtml(item.title)}</strong><span>${labels[item.type]||item.type} · 删除于 ${formatDate(item.deleted_at)}</span></div><div><button class="card-action" data-restore-content="${item.id}">恢复</button><button class="card-action danger-link" data-purge-content="${item.id}">永久删除</button></div></div>`).join(""):'<div class="empty-state compact">回收站是空的。</div>'}
function showUpdateStatus(result){const status=$("#updateStatus");status.replaceChildren(document.createTextNode(result.message||"更新检查完成。"));if(result.available&&result.installer_url){const link=document.createElement("a");link.href=result.installer_url;link.target="_blank";link.rel="noreferrer";link.textContent=" 下载官方安装包";status.appendChild(link)}}
function renderOnboarding(){$$('[data-onboarding-step]').forEach((step,index)=>step.hidden=index!==state.onboardingStep);$$('.onboarding-progress i').forEach((item,index)=>item.classList.toggle('active',index<=state.onboardingStep));$("#previousOnboarding").hidden=state.onboardingStep===0;$("#nextOnboarding").hidden=state.onboardingStep===2;$("#finishOnboarding").hidden=state.onboardingStep!==2}
function openOnboarding(){state.onboardingStep=0;renderOnboarding();if(!$("#onboardingDialog").open)$("#onboardingDialog").showModal()}
async function completeOnboarding(startCapture=false){try{await api("/api/onboarding/complete",{method:"POST",body:"{}"});state.system.onboarding_completed=true;$("#onboardingDialog").close();if(startCapture)$("#captureDialog").showModal()}catch(error){toast(error.message)}}
async function updateTask(id,status){await api(`/api/tasks/${id}`,{method:"PATCH",body:JSON.stringify({status})});await load();toast(status==="done"?"待办已完成":"待办已恢复")}
async function deleteContent(id){const item=state.contents.find(content=>content.id===Number(id));if(!item||!window.confirm(`确定把《${item.title}》移到回收站吗？之后仍然可以恢复。`))return;try{await api(`/api/contents/${id}`,{method:"DELETE"});if($("#editDialog").open)$("#editDialog").close();await load();toast("内容已移到回收站")}catch(error){toast(error.message)}}
function openTaskDialog(day=dateKey(new Date()),time=""){state.taskSourceId=null;$("#taskDate").value=day;$("#taskTime").value=time;$("#taskDialog").showModal()}

function switchView(view){$$('.view').forEach(el=>el.classList.remove("active"));$$('.nav-item').forEach(el=>el.classList.toggle("active",el.dataset.view===view));$(`#${view}View`).classList.add("active");const titles={today:"今天，继续向前一点",library:"交付依据资料库",chat:"和自己的知识对话",agentReview:"把 AI 候选变成可信草稿",review:"回头看，才能走得更远",settings:"设置"};$("#pageTitle").textContent=titles[view];$(".sidebar").classList.remove("open")}
function setFilter(filter){state.filter=filter;state.categoryFilter=null;$$('.filter').forEach(button=>button.classList.toggle("active",button.dataset.filter===filter));renderCategoryMap();renderLibrary()}
function addMessage(role,text,citations=[]){const el=document.createElement("div");el.className=`message ${role}`;el.textContent=text;if(citations.length){const list=document.createElement("div");list.className="citations";list.innerHTML=citations.map(item=>`<span class="citation">《${escapeHtml(item.title)}》</span>`).join("");el.appendChild(list)}$("#chatMessages").appendChild(el);el.scrollIntoView({behavior:"smooth",block:"nearest"})}
function bindEvents(){
  $("#pendingReviewMode").addEventListener("click",()=>{state.agentReviewMode="pending";renderAgentReview()});
  $("#reviewHistoryMode").addEventListener("click",()=>{state.agentReviewMode="history";renderAgentReview()});
  $("#agentReviewView").addEventListener("click",event=>{
    const historyItem=event.target.closest("[data-agent-review-history-id]");
    if(historyItem){state.activeAgentReviewHistoryId=Number(historyItem.dataset.agentReviewHistoryId);renderAgentReview();return}
    const output=event.target.closest("[data-review-output-deliverable]");
    if(output&&window.openCreatedDeliverable){window.openCreatedDeliverable(Number(output.dataset.reviewOutputProject),Number(output.dataset.reviewOutputDeliverable),Number(output.dataset.reviewOutputRevision));return}
    if(event.target.closest("[data-review-go-projects]")){state.agentReviewProjectId=null;switchView("projects")}
  });
  $("#agentReviewWorkspace").addEventListener("submit",async event=>{
    if(event.target.id!=="rejectCandidateForm")return;
    event.preventDefault();
    const item=activeAgentReview(),reason=$("#rejectCandidateReason").value.trim();
    if(!item||!reason)return;
    const button=event.target.querySelector("button"),status=$("#rejectCandidateStatus");
    button.disabled=true;
    try{
      await api(`/api/agent-candidate-results/${item.id}/reviews`,{method:"POST",body:JSON.stringify({decision:"rejected",actor:item.project.owner,actor_role:"project_owner",reason})});
      status.textContent="已记录拒绝原因；未创建交付物或版本。";
      await load();
      toast("候选已拒绝，正式交付内容不变");
    }catch(error){status.textContent=error.message;button.disabled=false;}
  });
  $("#sourceAccessFilter").addEventListener("change",renderLibrary);
  $$('.nav-item[data-view]').forEach(button=>button.addEventListener("click",()=>{if(button.dataset.view==="agentReview")state.agentReviewProjectId=null;switchView(button.dataset.view);if(button.dataset.view==="agentReview")renderAgentReview()}));
  $$('[data-view-jump]').forEach(button=>button.addEventListener("click",()=>{if(button.dataset.filter)setFilter(button.dataset.filter);switchView(button.dataset.viewJump)}));
  $("#menuButton").addEventListener("click",()=>$(".sidebar").classList.toggle("open"));
  $$('[data-open-capture]').forEach(button=>button.addEventListener("click",()=>$("#captureDialog").showModal()));
  $$('[data-close-modal]').forEach(button=>button.addEventListener("click",()=>$("#captureDialog").close()));
  $("#addTaskButton").addEventListener("click",()=>openTaskDialog());$$('[data-close-task]').forEach(button=>button.addEventListener("click",()=>$("#taskDialog").close()));$$('[data-close-edit]').forEach(button=>button.addEventListener("click",()=>$("#editDialog").close()));
  $$('.filter').forEach(button=>button.addEventListener("click",()=>setFilter(button.dataset.filter)));$("#librarySearch").addEventListener("input",renderLibrary);
  $("#categoryMap").addEventListener("click",event=>{const filter=event.target.closest('[data-category-filter]'),child=event.target.closest('[data-category-parent]'),edit=event.target.closest('[data-category-edit]');if(edit){openCategoryDialog(null,Number(edit.dataset.categoryEdit));return}if(child){openCategoryDialog(Number(child.dataset.categoryParent));return}if(filter){state.categoryFilter=filter.dataset.categoryFilter==="all"?null:Number(filter.dataset.categoryFilter);renderCategoryMap();renderLibrary()}});
  $("#addRootCategory").addEventListener("click",()=>openCategoryDialog());$$('[data-close-category]').forEach(button=>button.addEventListener("click",()=>$("#categoryDialog").close()));$("#categoryType").addEventListener("change",renderCategorySelects);
  $("#categoryForm").addEventListener("submit",async event=>{event.preventDefault();try{const editing=state.categoryEditId;await api(editing?`/api/categories/${editing}`:"/api/categories",{method:editing?"PATCH":"POST",body:JSON.stringify({name:$("#categoryName").value,content_type:$("#categoryType").value,parent_id:$("#categoryParent").value||null})});$("#categoryDialog").close();event.target.reset();$("#categoryType").disabled=false;state.categoryEditId=null;await load();toast(editing?"分类卡片已更新":"分类卡片已创建")}catch(error){toast(error.message)}});$("#deleteCategoryButton").addEventListener("click",async()=>{const category=categoryById(state.categoryEditId);if(!category||!window.confirm(`确定删除分类“${category.name}”吗？`))return;try{await api(`/api/categories/${category.id}`,{method:"DELETE"});$("#categoryDialog").close();$("#categoryType").disabled=false;state.categoryEditId=null;state.categoryFilter=null;await load();toast("分类卡片已删除")}catch(error){toast(error.message)}});
  $("#editType").addEventListener("change",renderCategorySelects);
  $("#libraryGrid").addEventListener("click",event=>{const edit=event.target.closest('[data-edit-content]'),task=event.target.closest('[data-task-content]'),remove=event.target.closest('[data-delete-content]');if(remove){deleteContent(remove.dataset.deleteContent);return}if(edit){const item=state.contents.find(content=>content.id===Number(edit.dataset.editContent));state.editId=item.id;$("#editTitle").value=item.title;$("#editBody").value=item.body||"";$("#editType").value=item.type;renderCategorySelects();$("#editCategory").value=item.category_id||"";$("#editTags").value=item.tags||"";$("#editDialog").showModal()}if(task){const item=state.contents.find(content=>content.id===Number(task.dataset.taskContent));openTaskDialog();state.taskSourceId=item.id;$("#taskTitle").value=`继续处理：${item.title}`}});
  $("#prevWeek").addEventListener("click",()=>{state.currentWeek=addDays(state.currentWeek,-7);renderWeekCalendar()});$("#nextWeek").addEventListener("click",()=>{state.currentWeek=addDays(state.currentWeek,7);renderWeekCalendar()});$("#currentWeek").addEventListener("click",()=>{state.currentWeek=startOfWeek(new Date());renderWeekCalendar()});
  $("#weekCalendar").addEventListener("click",async event=>{const task=event.target.closest('[data-calendar-task]');if(task){const item=state.tasks.find(entry=>entry.id===Number(task.dataset.calendarTask));await updateTask(item.id,item.status==="done"?"next":"done");return}const head=event.target.closest('[data-calendar-date]'),cell=event.target.closest('[data-cell-date]');const target=head||cell;if(target){const slot=cell?.dataset.cellSlot||"all",times={all:"",morning:"09:00",afternoon:"14:00",evening:"19:00"};openTaskDialog(target.dataset.calendarDate||target.dataset.cellDate,times[slot])}});
  $("#saveWeekPlan").addEventListener("click",async()=>{const weekStart=dateKey(state.currentWeek),planText=$("#weekPlanText").value;await api("/api/week-plan",{method:"POST",body:JSON.stringify({week_start:weekStart,plan_text:planText})});await load();toast("周计划已保存")});
  $("#weekPlanText").addEventListener("input",()=>{$("#weekPlanStatus").textContent="有未保存的修改"});
  $("#historyWeekSelect").addEventListener("change",event=>{state.historyWeek=event.target.value;renderTaskHistory()});
  $("#agentReviewQueue").addEventListener("click",event=>{const target=event.target.closest("[data-agent-review-id]");if(!target)return;state.activeAgentReviewId=Number(target.dataset.agentReviewId);state.selectedCandidateIndexes=defaultCandidateIndexes(activeAgentReview());renderAgentReview()});
  $("#agentReviewWorkspace").addEventListener("change",event=>{if(event.target.matches("#reviewTargetDeliverable")){updateReviewAction();return}const target=event.target.closest("[data-candidate-index]");if(!target)return;const index=Number(target.dataset.candidateIndex);state.selectedCandidateIndexes=target.checked?[...new Set([...state.selectedCandidateIndexes,index])]:state.selectedCandidateIndexes.filter(value=>value!==index);syncReviewDraft()});
  $("#agentReviewWorkspace").addEventListener("input",event=>{if(event.target.matches("#reviewedTitle,#reviewedDueDate,#reviewedAcceptanceCriteria,#reviewedScope,#reviewedOwner,#reviewedApprover,#reviewReason"))updateReviewAction()});
  $("#agentReviewWorkspace").addEventListener("submit",event=>{if(event.target.id!=="reviewCandidateForm")return;event.preventDefault();submitReviewedCandidate()});
  $$('.chat-tab').forEach(button=>button.addEventListener("click",()=>{$$('.chat-tab').forEach(tab=>tab.classList.toggle("active",tab===button));$$('.chat-workspace').forEach(tab=>tab.classList.remove("active"));$(`#${button.dataset.chatTab}Tab`).classList.add("active")}));
  $("#captureForm").addEventListener("submit",async event=>{event.preventDefault();try{await api("/api/contents",{method:"POST",body:JSON.stringify({title:$("#captureTitle").value,body:$("#captureBody").value,type:"knowledge",source:"manual"})});$("#captureDialog").close();event.target.reset();await load();switchView("library");toast("资料已保存；尚未授权给任何任务")}catch(error){toast(error.message)}});
  $("#taskForm").addEventListener("submit",async event=>{event.preventDefault();try{await api("/api/tasks",{method:"POST",body:JSON.stringify({title:$("#taskTitle").value,due_date:$("#taskDate").value,scheduled_time:$("#taskTime").value,priority:$("#taskPriority").value,source_content_id:state.taskSourceId})});$("#taskDialog").close();event.target.reset();state.taskSourceId=null;await load();toast("已加入待办")}catch(error){toast(error.message)}});
  $("#editForm").addEventListener("submit",async event=>{event.preventDefault();try{await api(`/api/contents/${state.editId}`,{method:"PATCH",body:JSON.stringify({title:$("#editTitle").value,body:$("#editBody").value,type:$("#editType").value,category_id:$("#editCategory").value||null,tags:$("#editTags").value})});$("#editDialog").close();await load();toast("知识内容已更新")}catch(error){toast(error.message)}});$("#deleteContentButton").addEventListener("click",()=>deleteContent(state.editId));
  $("#journalDraft").value=localStorage.getItem("journalDraft")||"";$("#journalDraft").addEventListener("input",event=>localStorage.setItem("journalDraft",event.target.value));
  $("#saveJournalButton").addEventListener("click",async()=>{const body=$("#journalDraft").value.trim();if(!body)return toast("先写一点今天的记录吧");await api("/api/contents",{method:"POST",body:JSON.stringify({title:new Date().toLocaleDateString("sv-SE")+" 日记",body,type:"journal",tags:"日常"})});$("#journalDraft").value="";localStorage.removeItem("journalDraft");await load();toast("今日日记已保存")});
  $("#knowledgeChatForm").addEventListener("submit",async event=>{event.preventDefault();const input=$("#knowledgeQuestion"),question=input.value.trim(),history=state.chatHistory,prior=history.map(({role,content})=>({role,content}));if(!question)return;history.push({role:"user",content:question});addMessage("user",question);input.value="";try{const result=await api("/api/chat",{method:"POST",body:JSON.stringify({message:question,history:prior})});history.push({role:"assistant",content:result.answer,citations:result.citations||[]});addMessage("assistant",result.answer,result.citations)}catch(error){history.push({role:"assistant",content:error.message});addMessage("assistant",error.message)}});
  $("#archiveDate").value=new Date().toLocaleDateString("sv-SE");$("#archiveForm").addEventListener("submit",async event=>{event.preventDefault();const resultEl=$("#archiveResult");resultEl.textContent="正在读取新增内容……";resultEl.classList.remove("empty-state");try{const result=await api("/api/chat-import",{method:"POST",body:JSON.stringify({path:$("#chatPath").value,date:$("#archiveDate").value})});resultEl.textContent=result.summary;await load();toast(result.archived?"当日对话已归档到知识库":`已读取 ${result.files||0} 个文件，请先配置 AI 服务`)}catch(error){resultEl.textContent=error.message}});
  $("#archiveAllSources").addEventListener("click",async()=>{const button=$("#archiveAllSources"),resultEl=$("#archiveResult"),sources=[...state.chatRegistrations];if(!sources.length)return;button.disabled=true;button.textContent="正在归档……";resultEl.classList.remove("empty-state");resultEl.textContent=`正在检查 ${sources.length} 个聊天来源……`;const lines=[];let archived=0;for(const source of sources){try{const result=await api("/api/chat-import",{method:"POST",body:JSON.stringify({path:source.path,date:$("#archiveDate").value})});if(result.archived){archived++;lines.push(`${source.display_name}：已生成当日归档`)}else if(result.needsSetup){lines.push(`${source.display_name}：发现新增内容，请先配置 AI 服务`)}else{lines.push(`${source.display_name}：没有新增内容`)}}catch(error){lines.push(`${source.display_name}：${error.message}`)}resultEl.textContent=lines.join("\n")};await load();button.textContent="归档今日全部来源";button.disabled=!state.chatRegistrations.length;toast(archived?`已生成 ${archived} 条当日聊天知识`:"全部来源检查完成")});
  $("#markdownImportForm").addEventListener("submit",async event=>{event.preventDefault();const selected=[...$("#markdownFiles").files],resultEl=$("#markdownImportResult");if(!selected.length)return toast("请选择 Markdown 文件");resultEl.textContent="正在导入……";resultEl.classList.remove("empty-state");try{const categoryId=$("#markdownCategory").value||null;const files=await Promise.all(selected.map(async file=>({name:file.name,relative_path:file.webkitRelativePath||file.name,category_id:categoryId,content:await file.text()})));const result=await api("/api/import-markdown",{method:"POST",body:JSON.stringify({files})});resultEl.textContent=`已导入 ${result.imported} 个文件${result.skipped?`，跳过 ${result.skipped} 个重复或无效文件`:""}。`;event.target.reset();await load();toast("聊天 Markdown 已进入知识库")}catch(error){resultEl.textContent=error.message}});
  $("#createBackupButton").addEventListener("click",async()=>{const button=$("#createBackupButton");button.disabled=true;$("#backupStatus").textContent="正在创建完整备份……";try{const result=await api("/api/backups",{method:"POST",body:"{}"});await load();$("#backupSelect").value=result.name;$("#restoreBackupButton").disabled=false;$("#backupStatus").textContent=`已创建 ${formatDate(result.created_at)} 的完整备份。`;toast("完整备份已创建")}catch(error){$("#backupStatus").textContent=error.message}finally{button.disabled=false}});
  $("#backupSelect").addEventListener("change",event=>{$("#restoreBackupButton").disabled=!event.target.value});
  $("#restoreBackupButton").addEventListener("click",async()=>{const name=$("#backupSelect").value;if(!name||!window.confirm("确定恢复所选备份吗？当前状态会先自动备份，然后替换为所选版本。"))return;const button=$("#restoreBackupButton");button.disabled=true;$("#backupStatus").textContent="正在校验并恢复备份……";try{await api("/api/backups/restore",{method:"POST",body:JSON.stringify({name})});await load();$("#backupStatus").textContent="恢复完成；恢复前的状态也已自动备份。";toast("备份已恢复")}catch(error){$("#backupStatus").textContent=error.message}finally{button.disabled=false}});
  $("#trashList").addEventListener("click",async event=>{const restore=event.target.closest('[data-restore-content]'),purge=event.target.closest('[data-purge-content]');try{if(restore){await api(`/api/contents/${restore.dataset.restoreContent}/restore`,{method:"POST",body:"{}"});await load();toast("内容已恢复")}if(purge){const item=state.trash.find(content=>content.id===Number(purge.dataset.purgeContent));if(!item||!window.confirm(`永久删除《${item.title}》吗？Markdown 文件也会被移除，且无法撤销。`))return;await api(`/api/trash/${item.id}`,{method:"DELETE"});await load();toast("内容已永久删除")}}catch(error){toast(error.message)}});
  $("#reopenOnboarding").addEventListener("click",openOnboarding);$("#nextOnboarding").addEventListener("click",()=>{state.onboardingStep=Math.min(2,state.onboardingStep+1);renderOnboarding()});$("#previousOnboarding").addEventListener("click",()=>{state.onboardingStep=Math.max(0,state.onboardingStep-1);renderOnboarding()});$("#skipOnboarding").addEventListener("click",()=>completeOnboarding());$("#finishOnboarding").addEventListener("click",()=>completeOnboarding(true));
  $("#checkUpdateButton").addEventListener("click",async()=>{const button=$("#checkUpdateButton");button.disabled=true;$("#updateStatus").textContent="正在检查正式发布渠道…";try{showUpdateStatus(await api("/api/update/check"))}catch(error){$("#updateStatus").textContent=error.message}finally{button.disabled=false}});
  $("#settingsForm").addEventListener("submit",async event=>{event.preventDefault();await api("/api/settings",{method:"POST",body:JSON.stringify({base_url:$("#baseUrl").value,model:$("#modelName").value,api_key:$("#apiKey").value})});await load();toast("设置已保存到本机")});
}

document.addEventListener("DOMContentLoaded",async()=>{bindEvents();renderChatMode();const now=new Date();$("#eyebrow").textContent=`${new Intl.DateTimeFormat("en-US",{weekday:"long"}).format(now).toUpperCase()} · ${String(now.getMonth()+1).padStart(2,"0")} / ${String(now.getDate()).padStart(2,"0")}`;try{await load()}catch(error){toast(error.message)}});
